"Resource/UI/HudDamageAccount.res"
{
	"CDamageAccountPanel"
	{
		"fieldName"				"CDamageAccountPanel"
		"text_x"				"0"
		"text_y"				"0"
		"delta_item_end_y"		"0"
		"PositiveColor"			"255 255 0 255"
		"NegativeColor"			"255 255 0 255"
		"delta_lifetime"		"2"
		"delta_item_font"		"CustomFont"
		"delta_item_font_big"	"CustomFontBig"
	}
	"DamageAccountValue"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"DamageAccountValue"
		"xpos"			"c-53"
		"ypos"			"r150"
		"zpos"			"2"
		"wide"			"100"
		"tall"			"50"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%metal%"
		"textAlignment"	"center"
		"fgcolor"		"Damage"
		"font"			"CustomFontBigger"
	}
	"DamageAccountValueBorder1"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"DamageAccountValue"
		"xpos"			"c-52"
		"ypos"			"r149"
		"zpos"			"2"
		"wide"			"100"
		"tall"			"50"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%metal%"
		"textAlignment"	"center"
		"fgcolor"		"Black1"
		"font"			"CustomFontBigger"
	}
	"DamageAccountValueBorder2"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"DamageAccountValue"
		"xpos"			"c-51"
		"ypos"			"r150"
		"zpos"			"2"
		"wide"			"100"
		"tall"			"50"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%metal%"
		"textAlignment"	"center"
		"fgcolor"		"Black1"
		"font"			"CustomFontBigger"
	}
	"DamageAccountValueBorder3"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"DamageAccountValue"
		"xpos"			"c-52"
		"ypos"			"r151"
		"zpos"			"2"
		"wide"			"100"
		"tall"			"50"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%metal%"
		"textAlignment"	"center"
		"fgcolor"		"Black1"
		"font"			"CustomFontBigger"
	}
	"DamageAccountValueBorder4"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"DamageAccountValue"
		"xpos"			"c-53"
		"ypos"			"r152"
		"zpos"			"2"
		"wide"			"100"
		"tall"			"50"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%metal%"
		"textAlignment"	"center"
		"fgcolor"		"Black1"
		"font"			"CustomFontBigger"
	}
	"DamageAccountValueBorder5"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"DamageAccountValue"
		"xpos"			"c-53"
		"ypos"			"r149"
		"zpos"			"2"
		"wide"			"100"
		"tall"			"50"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%metal%"
		"textAlignment"	"center"
		"fgcolor"		"Black1"
		"font"			"CustomFontBigger"
	}
	"DamageAccountValueBorder6"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"DamageAccountValue"
		"xpos"			"c-54"
		"ypos"			"r149"
		"zpos"			"2"
		"wide"			"100"
		"tall"			"50"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%metal%"
		"textAlignment"	"center"
		"fgcolor"		"Black1"
		"font"			"CustomFontBigger"
	}
	"DamageAccountValueBorder7"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"DamageAccountValue"
		"xpos"			"c-54"
		"ypos"			"r150"
		"zpos"			"2"
		"wide"			"100"
		"tall"			"50"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%metal%"
		"textAlignment"	"center"
		"fgcolor"		"Black1"
		"font"			"CustomFontBigger"
	}
	"DamageAccountValueBorder8"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"DamageAccountValue"
		"xpos"			"c-54"
		"ypos"			"r151"
		"zpos"			"2"
		"wide"			"100"
		"tall"			"50"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%metal%"
		"textAlignment"	"center"
		"fgcolor"		"Black1"
		"font"			"CustomFontBigger"
	}
	"DamageAccountValueBorder9"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"DamageAccountValue"
		"xpos"			"c-51"
		"ypos"			"r149"
		"zpos"			"2"
		"wide"			"100"
		"tall"			"50"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%metal%"
		"textAlignment"	"center"
		"fgcolor"		"Black1"
		"font"			"CustomFontBigger"
	}
	"DamageAccountValueBorder10"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"DamageAccountValue"
		"xpos"			"c-51"
		"ypos"			"r151"
		"zpos"			"2"
		"wide"			"100"
		"tall"			"50"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%metal%"
		"textAlignment"	"center"
		"fgcolor"		"Black1"
		"font"			"CustomFontBigger"
	}
	"DamageAccountValueBorder11"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"DamageAccountValue"
		"xpos"			"c-52"
		"ypos"			"r152"
		"zpos"			"2"
		"wide"			"100"
		"tall"			"50"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%metal%"
		"textAlignment"	"center"
		"fgcolor"		"Black1"
		"font"			"CustomFontBigger"
	}
	"DamageAccountValueBorder12"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"DamageAccountValue"
		"xpos"			"c-54"
		"ypos"			"r152"
		"zpos"			"2"
		"wide"			"100"
		"tall"			"50"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%metal%"
		"textAlignment"	"center"
		"fgcolor"		"Black1"
		"font"			"CustomFontBigger"
	}
	"DamageAccountValueBorder13"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"DamageAccountValue"
		"xpos"			"c-51"
		"ypos"			"r152"
		"zpos"			"2"
		"wide"			"100"
		"tall"			"50"
		"visible"		"1"
		"enabled"		"1"
		"labelText"		"%metal%"
		"textAlignment"	"center"
		"fgcolor"		"Black1"
		"font"			"CustomFontBigger"
	}
	"DamageAccountValueShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"DamageAccountValue"
		"xpos"			"c-51"
		"ypos"			"r149"
		"zpos"			"2"
		"wide"			"100"
		"tall"			"50"
		"visible"		"0"
		"enabled"		"1"
		"labelText"		"%metal%"
		"textAlignment"	"center"
		"fgcolor"		"Black1"
		"font"			"CustomFontBigger"
	}
}